### ISSUE TITLE
Respect Milestone Filtered Page

### ISSUE THREAD

**Issue by amykmeyers** [RallyCommunity/custom-grid-with-deep-export#14]
Is it possible to update the deep export to respect a selected milestone on a milestone filtered page?

**Comment by krmorse** [comment]
@amykmeyers i think i have it fixed, if you'd be willing to test it in html form: https://raw.githubusercontent.com/RallyCommunity/custom-grid-with-deep-export/dc1da13f6400bf499610d73f1599bcf339819c74/deploy/App.txt

If that looks good to you we'll get it merged into the production community app catalog on rally1.

**Comment by amykmeyers** [comment]
Thank you @krmorse - I will test and let you know what we finds

**Comment by krmorse** [comment]
@amykmeyers based on our internal testing this all looks good, so we're going to get it merged.  let me know if you find anything weird in your testing!

**Comment by krmorse** [comment]
Fixed in v1.1.3
