### ISSUE TITLE
Merge with Tech Services Version

### ISSUE THREAD

**Issue by sherimoore** [RallyCommunity/custom-grid-with-deep-export#20]
Hi @krmorse Here is another community app that we are hoping can be merged with the Tech Services version so that we don't miss out on any of the updates that come out of the community.  Is this something you might be able to take up now that Tyr is gone?  https://github.com/RallyTechServices/custom-grid-with-deep-export

**Comment by krmorse** [comment]
Unfortunately, I'm not sure what all changes have been made to the tech services version of the app, and most likely they wouldn't be backwards compatible.  We wouldn't want to break a ton of existing customers' custom list community apps.  

I'm also not sure what exactly this sort of work might even look like going forward in the new world of HCL.  In general Rally engineering has not done this sort of work...

Another complicating factor is that I also am moving on from Rally.
