### ISSUE TITLE
change _buildStore to sort by local priority?

### ISSUE THREAD

**Issue by shorsher** [RallyCommunity/custom-grid-with-deep-export#4]
My team is using this app and requires the need to sort their lists Features,etc by  **c_LocalPriority**.  I have changed _buildStore() to add a sorter as seen below:

```
_buildStore: function(){
        this.modelNames = [this.getSetting('type')];
        this.logger.log('_buildStore', this.modelNames);
        var fetch = ['FormattedID', 'Name', 'c_LocalPriority'];

        Ext.create('Rally.data.wsapi.TreeStoreBuilder').build({
            models: this.modelNames,
            enableHierarchy: true,
            fetch: fetch,
            sorters: [{property: "c_LocalPriority"}],
            sortOnLoad: true
        }).then({
            success: this._addGridboard,
            scope: this
        });
    } 
```

However, this only seems to work for UserStories.  When I change the app settings to display Features, it no longer provides any sorting.  

Was hoping I could get pointed in the right direction here, thanks!

EDIT:  I know you can do manually in the grid view, however, this piece is part of a bigger project where I would like to be able to export to CSV and preserve the c_LocalPriority ordering within the CSV.

**Comment by krmorse** [comment]
I would think it should export in the same order as however the grid is currently sorted, but it doesn't seem like it's doing that either...  Is that the real bug?  That export should respect the order of the current view?  I traced through the code that is loading all the data to export and it's not specifying any sorters at all...

**Comment by shorsher** [comment]
Yes, the end goal is to have the export respect the order of the current view, and it does not seem to be doing that.  So yes that would be the real bug 😄  I can provide some screenshots if you would like.

**Comment by shorsher** [comment]
@krmorse as an update I managed to be able to export only **user stories** ordered by Local Priority by modifying fetchRoot() in hierarchy-loader.js

```
fetchRoot: function(){
        var fetch = this.fetch.concat(this.getRequiredFetchFields(this.model));
        this.fireEvent('statusupdate', "Loading artifacts");
        var config = {
            model: this.model,
            fetch: fetch,
            filters: this.filter,
            sorters: [{property: "c_LocalPriority"}],
            sortOnLoad: true
        };
        this.logger.log('fetchRoot config', config);

        return this.fetchWsapiRecords(config);
    },
```
However this does not seem to apply when trying to export features.  Could you provide some insight as to why sorters do not seem to have an effect on features?

Currently just trying to find a workaround, but I'd be happy to work together with you to address the actual problem.

**Comment by krmorse** [comment]
I think I fixed it if you want to test.  #5 is the pull request.  You can manually test the code in a custom html panel using this: https://raw.githubusercontent.com/RallyCommunity/custom-grid-with-deep-export/2e889b8b5a35cc5e17d20f29b6711383de2a68d8/deploy/App.txt

**Comment by shorsher** [comment]
awesome I'll give it shot and report back here.  Regardless, thanks so much for the quick response back!

**Comment by shorsher** [comment]
@krmorse  It works great!  I did add an additional comment in #5 regarding one comment I had regarding some missing functionality.  

Once again, thanks so much!

**Comment by krmorse** [comment]
ok, cool- one more crack at it.  the story and task children will always be sorted by rank now in the export, just as they are in the grid view: https://raw.githubusercontent.com/RallyCommunity/custom-grid-with-deep-export/811caa1e95db7a375100308cf2935fff8b859009/deploy/App.txt

**Comment by shorsher** [comment]
awesome, appreciate all your work

**Comment by krmorse** [comment]
This fix will be available in the in-product community app catalog later this week @shorsher

**Comment by shorsher** [comment]
@krmorse  awesome!  does your latest PR include the story and task children sorting?  Just pulled the latest changes and it seems to be missing that functionality.  I can submit one if you would like, unless that is not desired in the app.

**Comment by shorsher** [comment]
@krmorse  I'm not entirely sure if the story/task children functionality is working.  I've included some screenshots of just local priority ordering in grid view and then exported CSV for the first feature and it's user stories as an example.  

**Grid Ordering**
<img width="352" alt="screen shot 2018-05-02 at 9 00 57 am" src="https://user-images.githubusercontent.com/10987380/39524680-b38c7d0a-4de7-11e8-9af6-9f927ed2ac63.png">



**Exported Ordering**
<img width="631" alt="screen shot 2018-05-02 at 9 01 20 am" src="https://user-images.githubusercontent.com/10987380/39524703-c8cb87ba-4de7-11e8-8ed8-43818553ccce.png">

**Comment by krmorse** [comment]
hmm, so in the grid view both your features and stories have a field called local priority?  and the stories are actually sorted that way too?  from digging through the code it seemed to me like children would always be rank ordered.

**Comment by shorsher** [comment]
yes correct on both points.  

If this isn't desired functionality on your end, no need to worry about it.  I just assumed that LocalPriority always existed as a field, but I am somewhat new to using rally.
