### ISSUE TITLE
Newly added grid columns do not persist when page is viewed by others

### ISSUE THREAD

**Issue by shorsher** [RallyCommunity/custom-grid-with-deep-export#6]
Not sure if this is a bug or not, however:

I have a custom report with the custom-grid-with-deep-export app placed on the page.  Let's say I add a new column, i.e. creation date, to the custom grid in addition to the default ID & Name.  If I share this page with another individual on my team, **they are not able to see the new columns I have added to the grid.**  

Is this intended?

**Comment by krmorse** [comment]
it is by design.  sorts, columns, filters are all user level prefs.  if you want to be able to share these views you should use one of the built-in apps like custom list for that.  this app really is specifically for exporting hierarchies

**Comment by shorsher** [comment]
awesome, thanks!

**Comment by krmorse** [comment]
I was hoping there would be some documentation around this in the [state guide](https://help.rallydev.com/apps/2.1/doc/#!/guide/state) but there's not.  Let me do some digging...

I think we can make it scope its state differently by specifying a correct state id, but I need to play with it a bit...

**Comment by shorsher** [comment]
yeah no worries, for the mean time I just added a work around hard-coding the columns required to be seen by all parties.
